"""Write the local render baseline for ``tests/test_render_smoke.py`` on the CURRENT NegPy pin.

Renders every raw in ``NEGMCP_TEST_ARW`` (one path, or several joined by ``os.pathsep``) in
both output modes at the iteration size (output long edge 2200) with the frozen CONFIG
below, and records the pixel SHA-256 + fingerprint of each. The baseline is personal data
(your scans), so it is written OUTSIDE the repo: ``$NEGMCP_TEST_BASELINE_DIR`` (default
``~/.cache/negmcp/test-baseline``). Run after a pin move — pixels legitimately change:

    NEGMCP_TEST_ARW=/path/to/scan.ARW python tests/fixtures/make_baseline.py
"""

from __future__ import annotations

import hashlib
import json
import os
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np

ITER_LONG_EDGE = 2200
# Frozen, neutral config: the fixture must not move when a look or recipe does.
CONFIG = {
    "process_mode": "C41",
    "crosstalk_profile": "kodak_gold_200",
    "color_separation": 1.1,
    "auto_exposure": True,
    "auto_normalize_contrast": True,
}


def scan_paths() -> list[Path]:
    raw = os.environ.get("NEGMCP_TEST_ARW", "")
    return [Path(p).expanduser() for p in raw.split(os.pathsep) if p]


def baseline_path(version: str) -> Path:
    """``0.62.0`` -> ``<dir>/baseline_062.json`` (major + 2-digit minor; the file holds the full version)."""
    major, minor = version.split(".")[:2]
    root = Path(os.environ.get("NEGMCP_TEST_BASELINE_DIR", "~/.cache/negmcp/test-baseline")).expanduser()
    return root / f"baseline_{major}{int(minor):02d}.json"


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def render_entry(arw: Path, ws: bool) -> dict:
    from negmcp import metrics, render

    im = render.render(str(arw), {**CONFIG, "output_working_space": ws}, output_long_edge=ITER_LONG_EDGE)
    fp = metrics.fingerprint(im)
    return {
        "sha256": hashlib.sha256(np.asarray(im).tobytes()).hexdigest(),
        "size": list(im.size),
        "fingerprint": {k: (round(v, 5) if isinstance(v, float) else [round(x, 5) for x in v]) for k, v in fp.items()},
    }


def _job(args: tuple[str, bool]) -> tuple[str, dict]:
    arw, ws = Path(args[0]), args[1]
    return f"{arw.name}_ws{int(ws)}", {**render_entry(arw, ws), "arw_sha256": file_sha256(arw)}


def main() -> None:
    from negmcp import _negpy

    arws = scan_paths()
    if not arws:
        raise SystemExit("set NEGMCP_TEST_ARW to one or more raw scans (os.pathsep-separated)")
    pin = _negpy.read_pin()
    jobs = [(str(a), ws) for a in arws for ws in (False, True)]
    with ProcessPoolExecutor(min(len(jobs), max(1, (os.cpu_count() or 4) - 2))) as ex:
        frames = dict(ex.map(_job, jobs))
    out = {
        "_note": "render(output_long_edge=2200) of CONFIG per output mode; sha256 = np.asarray(image).tobytes(). "
        "Generated by tests/fixtures/make_baseline.py.",
        "negpy": pin.version,
        "negpy_commit": pin.commit,
        "iter_long_edge": ITER_LONG_EDGE,
        "config": CONFIG,
        "frames": frames,
    }
    path = baseline_path(pin.version)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(out, indent=1) + "\n")
    print(f"{path} ({len(frames)} frames)")


if __name__ == "__main__":
    main()
